# Generated by Django 3.2.6 on 2021-08-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0005_alter_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularcars',
            old_name='make',
            new_name='brand',
        ),
    ]
