# Generated by Django 3.2.6 on 2021-08-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0006_rename_make_popularcars_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularcars',
            old_name='url',
            new_name='image_url',
        ),
    ]
