# Generated by Django 3.2.6 on 2021-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0007_rename_url_popularcars_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcars',
            name='image_url',
            field=models.ImageField(blank=True, default='images/white_img.png', null=True, upload_to=''),
        ),
    ]
