# Generated by Django 3.2.6 on 2021-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0008_alter_popularcars_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcars',
            name='site',
            field=models.CharField(default=None, help_text='index', max_length=200),
        ),
    ]
