# Generated by Django 3.2.6 on 2021-08-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0010_auto_20210830_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularcars',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
