# Generated by Django 3.2.6 on 2021-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0011_popularcars_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image_url',
            field=models.ImageField(blank=True, default='images/white_img.png', null=True, upload_to='images/used/'),
        ),
    ]
